pkg(edit): perl 5.40.2
Renovations

diff --git a/perl/pkg b/perl/pkg
--- a/perl/pkg
+++ b/perl/pkg
@@ -8,7 +8,7 @@ MAJOR="${MINOR%.*}"
 
 a="The Practical Extrarction and Report Language"
 m="Tox"
-l="Artistic-1.0-Perl OR GPL-1.0-or-later"
+l="Artistic-1.0-${n^} OR GPL-1.0-or-later"
 t="core lang"
 u="https://github.com/${n^}/${n}${MAJOR}.git"
 # The below vf filters for even minor parts, then official releases
@@ -16,9 +16,13 @@ vf="gr | vfem | vfs"
 
 s=(
     "${u%.git}/archive/refs/tags/v$v.tar.gz"
+    "https://www.linuxfromscratch.org/patches/lfs/development/$n-$v-upstream_fix-1.patch"
 )
 
 d=(
+    "b,iana-etc"
+    "b,procps-ng"
+    "gcc"
     "gdbm"
     "glibc"
     "libxcrypt"
@@ -26,20 +30,22 @@ d=(
 
 b() {
 
+pat "$S/$n-$v-upstream_fix-1.patch"
+
 export BUILD_ZLIB=False
 export BUILD_BZIP2=0
 
 NO_DEFAULT=1
 _cfg=(
-    -des
+    -de
     -D prefix=/usr
     -D vendorprefix=/usr
-    -D privlib=/usr/lib/perl$MAJOR/$MINOR/core_perl
-    -D archlib=/usr/lib/perl$MAJOR/$MINOR/core_perl
-    -D sitelib=/usr/lib/perl$MAJOR/$MINOR/site_perl
-    -D sitearch=/usr/lib/perl$MAJOR/$MINOR/site_perl
-    -D vendorlib=/usr/lib/perl$MAJOR/$MINOR/vendor_perl
-    -D vendorarch=/usr/lib/perl$MAJOR/$MINOR/vendor_perl
+    -D privlib=/usr/lib/${n}${MAJOR}/${MINOR}/core_${n}
+    -D archlib=/usr/lib/${n}${MAJOR}/${MINOR}/core_${n}
+    -D sitelib=/usr/lib/${n}${MAJOR}/${MINOR}/site_${n}
+    -D sitearch=/usr/lib/${n}${MAJOR}/${MINOR}/site_${n}
+    -D vendorlib=/usr/lib/${n}${MAJOR}/${MINOR}/vendor_${n}
+    -D vendorarch=/usr/lib/${n}${MAJOR}/${MINOR}/vendor_${n}
     -D man1dir=/usr/share/man/man1
     -D man3dir=/usr/share/man/man3
     -D pager="/usr/bin/less -isR"
@@ -52,3 +58,12 @@ ln -sv {C,c}onfigure
 def
 
 }
+
+# Tests take about 4 years to run. I observed 1 failure.
+# t() {
+#
+# # TODO: Write a helper in base.env to parse jobs from makeflags
+# # TEST_JOBS=$(nproc) make test_harness
+# make test || true
+#
+# }
