pkg(bump): nvidia 575.51.02 -> 575.57.08
Overhaul, bump

diff --git a/nvidia/pkg b/nvidia/pkg
--- a/nvidia/pkg
+++ b/nvidia/pkg
@@ -1,7 +1,9 @@
 #!/to
+# Huge thanks to Zeckma
+# https://github.com/glfs-book/glfs/blob/trunk/shareddeps/drivers/nvidia.xml
 
 n="nvidia"
-v="575.51.02"
+v="575.57.08"
 a="${n^^} drivers"
 m="Tox"
 l="Custom"
@@ -11,132 +13,145 @@ vf="curl -s https://api.github.com/repos/${n^^}/open-gpu-kernel-modules/releases
 
 s=(
     "https://us.download.$n.com/XFree86/Linux-x86_64/$v/${n^^}-Linux-x86_64-$v.run"
-    "https://glfs-book.github.io/glfs/patches/$n/$n-$v-gcc15.patch"
+    "https://glfs-book.github.io/glfs/patches/$n/$n-$v-kernel_gpl_cachyos-1.patch"
 )
 
 d=(
+    "mesa"
     "libglvnd"
     "kernel"
     "b,libelf"
 )
 
+nvsym() {
+    soname=$(readelf -d $1.so.*.*.* |
+        grep '(SONAME)' | sed -n 's/.*\[\(.*\)\]/\1/p')
+
+    if test -n $soname; then
+        test -e $(dirname $1)/$soname ||
+            ln -svf $1.so.*.*.* $(dirname $1)/$soname
+        test -e $1.so ||
+            ln -svf $soname $1.so
+    fi
+}
+
 b() {
-
-chmod +x "$S/NVIDIA-Linux-x86_64-$v.run"
-"$S/${n^^}-Linux-x86_64-$v.run" -x
-cd "${n^^}-Linux-x86_64-$v"
-
-pat "$S/$n-$v-gcc15.patch" -d kernel
-pat "$S/$n-$v-gcc15.patch" -d kernel-open
 
 kver=$(</usr/src/linux/version)
 
+sh "$S/${n^^}-Linux-x86_64-$v.run" -x
+cd "${n^^}-Linux-x86_64-$v"
+
+# Patch NVIDIA's broken ass drivers
+patch -d kernel -Np1 -i "$S/$n-$v-kernel_gpl_cachyos-1.patch"
+
+# Build and install modules
+cd kernel-open
 _cfg=(
-    --silent
-    --ui=none
-    --no-rpms
-    --no-x-check
-    --no-peermem
-    --no-systemd
-    --no-abi-note
-    --no-questions
-    --x-prefix=/usr
-    --disable-nouveau
-    --skip-module-load
-    --no-nouveau-check
-    --no-ncurses-color
-    --force-selinux=no
-    --kernel-name=$kver
-    --no-install-libglvnd
-    --no-rebuild-initramfs
-    --no-install-compat32-libs
-    --kernel-module-type=proprietary
-    --no-check-for-alternate-installs
-    --kernel-source-path=/usr/src/linux
-    --allow-installation-with-running-driver
-    --kernel-install-path="$D"/usr/lib/modules/$kver/kernel/drivers/video
+    KERNEL_SOURCES="/usr/src/linux"
+    KERNEL_UNAME="$kver"
+    KERNEL_MODLIB="$D/usr/lib/modules/$kver"
+    NV_EXCLUDE_KERNEL_MODULES="$n-peermem $n-uvm"
 )
+mk "${_cfg[@]}"
+mk "${_cfg[@]}" modules_install
+cd ..
 
-echo "Building $n@$v for kernel@$kver..." >&2
-# TODO: DKMS that shit
-./nvidia-installer "${_cfg[@]}"
-
-# Install NVIDIA components
-
-## Libraries
-
-### X driver
-install -vDm755 "${n}_drv.so"                   -t "$D/usr/lib/xorg/modules/drivers/"
-
-### Firmware (Turing)
+# Install firmware
 install -vDm644 "firmware/gsp_tu10x.bin"        -t "$D/usr/lib/firmware/$n/$v/"
 
-### Misc
-install -vDm755 "lib$n-allocator.so.$v"         -t "$D/usr/lib"
-install -vDm755 "lib$n-api.so.1"                -t "$D/usr/lib"
-install -vDm755 "lib$n-cfg.so.$v"               -t "$D/usr/lib"
-install -vDm755 "lib$n-encode.so.$v"            -t "$D/usr/lib"
-install -vDm755 "lib$n-fbc.so.$v"               -t "$D/usr/lib"
-install -vDm755 "lib$n-glvkspirv.so.$v"         -t "$D/usr/lib"
-install -vDm755 "lib$n-gpucomp.so.$v"           -t "$D/usr/lib"
-install -vDm755 "lib$n-ml.so.$v"                -t "$D/usr/lib"
+# Mandatory software
+libs=(
+  lib$n-cfg
+  lib$n-eglcore
+  lib$n-glcore
+  lib$n-glsi
+  lib$n-glvkspirv
+  lib$n-gpucomp
+  lib$n-ml
+  lib$n-pkcs11
+  lib$n-tls
+  lib$n-allocator
+)
 
-### GLX stuff
-install -vDm755 "libglxserver_$n.so.$v"         -t "$D/usr/lib/$n/xorg/"
-ln -sv "libglxserver_$n.so.$v"                     "$D/usr/lib/$n/xorg/libglxserver_$n.so.1"
-ln -sv "libglxserver_$n.so.$v"                     "$D/usr/lib/$n/xorg/libglxserver_$n.so"
+for lib in ${libs[@]}; do
+    install -vDm755 $lib.so* -t "$D/usr/lib"
+    nvsym "$D/usr/lib/$lib" || die "Failed to install and symlink ${lib}"
+done
 
-### OpenGL
-install -vDm644 "10_$n.json"                    -t "$D/usr/share/glvnd/egl_vendor.d/"
-install -vDm755 "lib$n-eglcore.so.$v"           -t "$D/usr/lib/"
-install -vDm755 "lib$n-glcore.so.$v"            -t "$D/usr/lib/"
-install -vDm755 "lib$n-glsi.so.$v"              -t "$D/usr/lib/"
-install -vDm755 "libEGL_$n.so.$v"               -t "$D/usr/lib/"
-install -vDm755 "libGLESv2_$n.so.$v"            -t "$D/usr/lib/"
+install -vDm4755 "$n-modprobe"                  -t "$D/usr/bin/"
+install -vDm644  "$n-application-profiles"*     -t "$D/usr/share/$n/"
 
-### Vulkan
+
+# X11
+install -vDm755 "${n}_drv.so"*                  -t "$D/usr/lib/xorg/modules/drivers/"
+install -vDm755 "libglxserver_$n.so"*           -t "$D/usr/lib/xorg/modules/extensions/"
+
+ln -svf "libglxserver_$n.so".*.*.*  \
+    "$D/usr/lib/xorg/modules/extensions/libglxserver_$n.so.1"
+ln -svf "libglxserver_$n.so.1"      \
+    "$D/usr/lib/xorg/modules/extensions/libglxserver_$n.so"
+
+install -vDm755 "libGLX_$n.so"* "lib$n-fbc.so"* -t "$D/usr/lib/"
+
+nvsym "$D/usr/lib/libGLX_$n"
+nvsym "$D/usr/lib/lib$n-fbc"
+
+install -vDm644 "$n-drm-outputclass.conf"       -t "$D/usr/share/X11/xorg.conf.d/"
+
+# EGL
+libs=(
+    lib$n-egl-gbm
+    lib$n-egl-wayland
+    lib$n-egl-xcb
+    lib$n-egl-xlib
+    libEGL_$n
+    lib$n-wayland-client
+)
+for lib in ${libs[@]}; do
+    install -vDm755 "$lib.so"*                  -t "$D/usr/lib"
+    nvsym "$D/usr/lib/$lib" || die "Failed to install and symlink ${lib}"
+done
+
+install -vDm644 {10,15,20}*.json                -t "$D/usr/share/glvnd/egl_vendor.d/"
+
+# GLES v{2,3}
+install -vDm755 "libGLESv2_$n.so"*              -t "$D/usr/lib"
+nvsym "$D/usr/lib/libGLESv2_$n"
+
+# Vulkan
 install -vDm644 "${n}_icd.json"                 -t "$D/usr/share/vulkan/icd.d/"
-install -vDm644 "${n}_layers.json"              -t "$D/usr/share/vulkan/implicit_layer.d/"
 
-### VDPAU
-install -vDm755 "libvdpau_$n.so.$v"             -t "$D/usr/lib/vdpau/"
+# VDPAU
+install -vDm755 "libvdpau_$n.so"*               -t "$D/usr/lib/vdpau/"
+nvsym "$D/usr/lib/vdpau/libvdpau_$n"
 
-### CUDA
-install -vDm755 "libcuda.so.$v"                 -t "$D/usr/lib/"
-install -vDm755 "libnvcuvid.so.$v"              -t "$D/usr/lib/"
+# CUDA
+libs=(
+    libcuda
+    libcudadebugger
+    lib$n-encode
+    lib$n-opticalflow
+    lib$n-ptxjitcompiler
+    lib$n-nvvm
+    libnvcuvid
+)
+for lib in ${libs[@]}; do
+    install -vDm755 "$lib.so"*                  -t "$D/usr/lib/"
+    nvsym "$D/usr/lib/$lib" || die "Failed to install and symlink ${lib}"
+done
 
-### CUDA compiler infrastructure
-install -vDm644 "lib$n-nvvm.so.$v"              -t "$D/usr/lib/"
-install -vDm755 "lib$n-ptxjitcompiler.so.$v"    -t "$D/usr/lib/"
+install -vDm755 "lib$n-api"*                    -t "$D/usr/lib/"
+ln -svf "/usr/lib/lib$n-api.so.1" \
+        "/usr/lib/lib$n-api.so"
+install -vDm755 "lib$n-nvvm70"*                 -t "$D/usr/lib/"
 
-### Raytracing
-install -vDm755 "lib$n-rtcore.so.$v"            -t "$D/usr/lib/"
-install -vDm755 "libnvoptix.so.$v"              -t "$D/usr/lib/"
-install -vDm755 "nvoptix.bin"                   -t "$D/usr/share/$n/"
-
-### Optical flow
-install -vDm755 "lib$n-opticalflow.so.$v"       -t "$D/usr/lib/"
-
-### Application profiles
-install -vDm644 "$n-application-profiles-$v-rc" -t "$D/usr/share/$n/"
-
-## Programs
-
-### nvidia-xconfig
+# Utils
 install -vDm755 "$n-xconfig"                    -t "$D/usr/bin/"
-
-### nvidia-smi
 install -vDm755 "$n-smi"                        -t "$D/usr/bin/"
 
-### nvidia-modprobe
-# FIX: Remove setuid whenever NVIDIA gets their shit together
-install -vDm4755 "$n-modprobe"                  -t "$D/usr/bin"
-
-il
-install -vDm644 "README.txt"                       "$D/usr/share/doc/$n/README"
-
 # Create a DRI pkgconfig file for packages expecting one
-install -vDm644 /dev/stdin "$D"/usr/lib/pkgconfig/dri.pc << "EOF"
+install -vDm644 /dev/stdin "$D/usr/lib/pkgconfig/dri.pc" << EOF
 prefix=/usr
 includedir=\${prefix}/include
 
@@ -149,20 +164,30 @@ Requires.private: libdrm >= 2.4.109
 Cflags: -I\${includedir}
 EOF
 
-# Blacklist Nouveau
-install -vDm644 /dev/stdin "$D/usr/lib/modprobe.d/nvfb.conf" << "EOF"
+# Blacklist stuff necessary to have a functional tty
+install -vDm644 /dev/stdin "$D/usr/lib/modprobe.d/nvfb.conf" << EOF
 # /usr/lib/modprobe.d/nvfb.conf
 
-blacklist nvidiafb
+blacklist ${n}fb
 blacklist nouveau
+EOF
+
+# Blacklist stuff necessary to have a functional wayland
+install -vDm644 /dev/stdin "$D/usr/lib/modprobe.d/${n}_drm.conf" << EOF
+# /usr/lib/modprobe.d/${n}_drm.conf
+
+options ${n}_drm modeset=1
 EOF
 
 }
 
 i() {
 
+ln -svrf "/usr/lib/lib$n-allocator.so"  \
+         "/usr/lib/gbm/$n-drm_gbm.so"
+
 if to data -i xorg-server; then
-    nvidia-xconfig
+    $n-xconfig
 fi
 
 }
